# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "build/onos-a1t"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "test/utils/xapp/build/onos-a1txapp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "test/utils/xapp"
    schedule:
      interval: "weekly"
